### ISSUE TITLE
Unsupported platform for fsevents@2.3.2

### ISSUE THREAD

**Issue by chaindigital** [helikon-labs/substrate-simple-payout#426]
Hi, I'm trying to install this on Ubuntu 20 and encountered this problem after installing npm:

npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 689 packages from 353 contributors in 16.54s

89 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

root@ubuntu-4gb-hel1-2:~/substrate-simple-payout# npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 3.205s

89 packages are looking for funding
  run `npm fund` for details

fixed 0 of 0 vulnerabilities in 0 scanned packages

**Comment by chaindigital** [comment]
and npm start

> substrate-payout-service@1.0.0 prestart /root/substrate-simple-payout
> npm run build


> substrate-payout-service@1.0.0 build /root/substrate-simple-payout
> rimraf dist && tsc

/root/substrate-simple-payout/node_modules/rimraf/dist/esm/bin.mjs:2
import { readFile } from 'fs/promises';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! substrate-payout-service@1.0.0 build: `rimraf dist && tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the substrate-payout-service@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-04-30T10_29_19_062Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! substrate-payout-service@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the substrate-payout-service@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-04-30T10_29_19_077Z-debug.log

**Comment by kukabi** [comment]
Thanks for the report @ERNcrypto. What are your `npm` and `node` versions? I'm testing it successfully from scratch with `npm 8.19.2` and `node v16.13.0`.

**Comment by chaindigital** [comment]
> Thanks for the report @ERNcrypto. What are your `npm` and `node` versions? I'm testing it successfully from scratch with `npm 8.19.2` and `node v16.13.0`.

{ 'substrate-payout-service': '1.0.0',
  npm: '6.14.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.1',
  http_parser: '2.9.3',
  icu: '66.1',
  modules: '64',
  napi: '5',
  nghttp2: '1.40.0',
  node: '10.19.0',
  openssl: '1.1.1f',
  tz: '2024a',
  unicode: '13.0',
  uv: '1.34.2',
  v8: '6.8.275.32-node.55',
  zlib: '1.2.11' }

**Comment by kukabi** [comment]
@ERNcrypto it might be your `npm` and `node` versions. I can confirm it works with both of the below versions:

- `node v16.13.0` and `npm 8.19.2`
- `node v20.12.2` and `npm 10.5.0`

I had issues running it with `node v22.0.0`, but LTS version for `node` is `v20.12.2`. Can you please update your `node` & `npm` and try again?

Also, you probably did it, but don't forget to correctly fill the `.env` file as explained in the readme file.

**Comment by chaindigital** [comment]
> @ERNcrypto it might be your `npm` and `node` versions. I can confirm it works with both of the below versions:
> 
> * `node v16.13.0` and `npm 8.19.2`
> * `node v20.12.2` and `npm 10.5.0`
> 
> I had issues running it with `node v22.0.0`, but LTS version for `node` is `v20.12.2`. Can you please update your `node` & `npm` and try again?
> 
> Also, you probably did it, but don't forget to correctly fill the `.env` file as explained in the readme file.

The installation was successful, I was able to pay the rewards once, but the next time I try I get an error: 
root@ubuntu-4gb-hel1-2:~/substrate-simple-payout# npm start

> substrate-payout-service@1.0.0 prestart
> npm run build


> substrate-payout-service@1.0.0 build
> rimraf dist && tsc


> substrate-payout-service@1.0.0 start
> cross-env NODE_ENV=production node dist/index.js

2024-04-30T11:51:13.901Z INFO   Starting...
2024-04-30T11:51:13.905Z INFO   Single-run mode.
2024-04-30T11:51:13.905Z INFO   Get API connection.
(node:20842) [UNDICI-WS] Warning: WebSockets are experimental, expect them to change at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^

TypeError: Cannot read properties of null (reading 'length')
    at WebSocket.__internal__onSocketMessage (/root/substrate-simple-payout/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:397:40)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at WebSocket.dispatchEvent (node:internal/event_target:757:26)
    at fireEvent (node:internal/deps/undici/undici:10978:14)
    at websocketMessageReceived (node:internal/deps/undici/undici:11000:7)
    at ByteParser.run (node:internal/deps/undici/undici:11437:17)
    at ByteParser._write (node:internal/deps/undici/undici:11313:14)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)

Node.js v22.0.0

**Comment by kukabi** [comment]
@ERNcrypto I mentioned in my previous reply that `node v22.0.0` is problematic. Can you please try it with `node v20.12.2` or `v16.13.0`?

**Comment by chaindigital** [comment]
> @ERNcrypto I mentioned in my previous reply that `node v22.0.0` is problematic. Can you please try it with `node v20.12.2` or `v16.13.0`?

VEC: Unable to decode on index 0 createType(Lookup0):: Decoding  Gv7aohxceo5XqeDZzJzxR5fxGaZwQUzSpmRzNXSLFvJdv: Invalid base58 character " " (0x20) at index 0
2024-04-30 12:40:43        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding  Gv7aohxceo5XqeDZzJzxR5fxGaZwQUzSpmRzNXSLFvJdv: Invalid base58 character " " (0x20) at index 0
/root/substrate-simple-payout/node_modules/@polkadot/types-create/cjs/create/type.js:54
        firstError = new Error(`createType(${type}):: ${error.message}`);
                     ^

Error: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding  Gv7aohxceo5XqeDZzJzxR5fxGaZwQUzSpmRzNXSLFvJdv: Invalid base58 character " " (0x20) at index 0
    at createTypeUnsafe (/root/substrate-simple-payout/node_modules/@polkadot/types-create/cjs/create/type.js:54:22)
    at TypeRegistry.createTypeUnsafe (/root/substrate-simple-payout/node_modules/@polkadot/types/cjs/create/registry.js:230:52)
    at RpcCore._formatParams (/root/substrate-simple-payout/node_modules/@polkadot/rpc-core/cjs/bundle.js:300:34)
    at callWithRegistry (/root/substrate-simple-payout/node_modules/@polkadot/rpc-core/cjs/bundle.js:187:33)
    at Observable._subscribe (/root/substrate-simple-payout/node_modules/@polkadot/rpc-core/cjs/bundle.js:195:17)
    at Observable._trySubscribe (/root/substrate-simple-payout/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at /root/substrate-simple-payout/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
    at Object.errorContext (/root/substrate-simple-payout/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.subscribe (/root/substrate-simple-payout/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at ConnectableObservable.connect (/root/substrate-simple-payout/node_modules/rxjs/dist/cjs/internal/observable/ConnectableObservable.js:60:40)

Node.js v20.12.2

**Comment by chaindigital** [comment]
It seems clear what the issue is, when we list stash addresses, we need to put a comma between them with no space between them

**Comment by chaindigital** [comment]
Can I add multiple wallets to pay out rewards from different validators? 
For example wallet X requests rewards from 10 wallets in group A and wallet Y requests rewards from the other 10 wallets in group B?

**Comment by kukabi** [comment]
@ERNcrypto Unfortunately not, this program is kept very simple deliberately. It can be added into the code, but if you wouldn't like to do that then a rough solution is to copy it into another folder and run two instances with each its own `.env` file, configured for different wallets and stash addresses.
